Revise cache logic more
- Pass cache keys as step's outputs instead of shell env vars to make them reliable
- Save cache even for pull-request because it's saved only when whole steps are
  successful, cache size is reduced to <200MB, so it won't create cache too many
- Add action-write permission to delete cache when env.REFRESH_CACHE is true
- Don't strip symbols for linux builds since cache size is reduced to <200MB

LiteRT-LM-PiperOrigin-RevId: 772969570

diff --git a/.github/workflows/ci-build-mac.yml b/.github/workflows/ci-build-mac.yml
--- a/.github/workflows/ci-build-mac.yml
+++ b/.github/workflows/ci-build-mac.yml
@@ -26,6 +26,7 @@ jobs:
     name: "Presubmit-Mac"
     runs-on: macos-latest
     permissions:
+      actions: write  # For gh cache delete.
       contents: write  # For gh release upload.
     env:
       GH_TOKEN: ${{ github.token }}  # For gh release upload.
@@ -36,29 +37,30 @@ jobs:
         uses: actions/checkout@v4
 
       - name : Set up cache keys
+        id: cache-keys
         run: |
-          export CACHE_RESTORE_KEY_2="${{ github.workflow }}"
-          export CACHE_RESTORE_KEY_1="$CACHE_RESTORE_KEY_2-${{ hashFiles('**/WORKSPACE', '**/.bazelrc') }}"
-          export CACHE_RESTORE_KEY_0="$CACHE_RESTORE_KEY_1-${{ hashFiles('**/BUILD*') }}"
-          export CACHE_KEY="$CACHE_RESTORE_KEY_0-${{ github.sha }}"
-          echo "CACHE_RESTORE_KEY_2=$CACHE_RESTORE_KEY_2" >> "$GITHUB_ENV"
-          echo "CACHE_RESTORE_KEY_1=$CACHE_RESTORE_KEY_1" >> "$GITHUB_ENV"
-          echo "CACHE_RESTORE_KEY_0=$CACHE_RESTORE_KEY_0" >> "$GITHUB_ENV"
-          echo "CACHE_KEY=$CACHE_KEY" >> "$GITHUB_ENV"
+          CACHE_RESTORE_KEY_2="${{ github.workflow }}"
+          CACHE_RESTORE_KEY_1="$CACHE_RESTORE_KEY_2-${{ hashFiles('**/WORKSPACE', '**/.bazelrc') }}"
+          CACHE_RESTORE_KEY_0="$CACHE_RESTORE_KEY_1-${{ hashFiles('**/BUILD*') }}"
+          CACHE_KEY="$CACHE_RESTORE_KEY_0-${{ github.sha }}"
+          echo "CACHE_RESTORE_KEY_2=$CACHE_RESTORE_KEY_2" >> "$GITHUB_OUTPUT"
+          echo "CACHE_RESTORE_KEY_1=$CACHE_RESTORE_KEY_1" >> "$GITHUB_OUTPUT"
+          echo "CACHE_RESTORE_KEY_0=$CACHE_RESTORE_KEY_0" >> "$GITHUB_OUTPUT"
+          echo "CACHE_KEY=$CACHE_KEY" >> "$GITHUB_OUTPUT"
 
       - name: Restore bazel cache if cache is not being refreshed.
-        if: ${{ env.REFRESH_CACHE }} != 'true'
+        if: ! env.REFRESH_CACHE
         uses: actions/cache/restore@v4
         id: bazel-cache
         with:
           path: |
             ~/.cache/bazel-macos
             ~/.cache/bazel-ios
-          key: ${{ env.CACHE_KEY }}
+          key: ${{ steps.cache-keys.outputs.CACHE_KEY }}
           restore-keys: |
-            ${{ env.CACHE_RESTORE_KEY_0 }}-
-            ${{ env.CACHE_RESTORE_KEY_1 }}-
-            ${{ env.CACHE_RESTORE_KEY_2 }}-
+            ${{ steps.cache-keys.outputs.CACHE_RESTORE_KEY_0 }}-
+            ${{ steps.cache-keys.outputs.CACHE_RESTORE_KEY_1 }}-
+            ${{ steps.cache-keys.outputs.CACHE_RESTORE_KEY_2 }}-
 
       - name: Check cache hit
         run: |
@@ -91,14 +93,14 @@ jobs:
           gh release upload ${{ github.ref_name }} litert_lm_main.ios_sim_arm64 --clobber
 
       - name: Remove cache if cache is being refreshed.
-        if: ${{ env.REFRESH_CACHE }} == 'true'
-        run: gh cache delete ${{ env.CACHE_KEY }} || echo "Cache not found"
+        if: env.REFRESH_CACHE
+        run: gh cache delete ${{ steps.cache-keys.outputs.CACHE_KEY }} || echo "Cache not found"
 
-      - name: Save bazel cache if it's new and not triggered by pull request.
+      - name: Save bazel cache if it's new or being refreshed.
         uses: actions/cache/save@v4
-        if: steps.bazel-cache.outputs.cache-hit != 'true' && github.event_name != 'pull_request'
+        if: env.REFRESH_CACHE || steps.bazel-cache.outputs.cache-hit != 'true'
         with:
           path: |
             ~/.cache/bazel-macos
             ~/.cache/bazel-ios
-          key: ${{ env.CACHE_KEY }}
+          key: ${{ steps.cache-keys.outputs.CACHE_KEY }}
diff --git a/.github/workflows/ci-build-win.yml b/.github/workflows/ci-build-win.yml
--- a/.github/workflows/ci-build-win.yml
+++ b/.github/workflows/ci-build-win.yml
@@ -21,6 +21,7 @@ jobs:
     name: "Nightly-Win"
     runs-on: windows-latest
     permissions:
+      actions: write  # For gh cache delete.
       contents: write  # For gh release upload.
     env:
       # Clear ANDROID_NDK_HOME as windows-latest has NDK where jobs don't have permission for
@@ -33,27 +34,28 @@ jobs:
         uses: actions/checkout@v4
 
       - name : Set up cache keys
+        id: cache-keys
         run: |
-          $env:CACHE_RESTORE_KEY_2="${{ github.workflow }}"
-          $env:CACHE_RESTORE_KEY_1="$CACHE_RESTORE_KEY_2-${{ hashFiles('**/WORKSPACE', '**/.bazelrc') }}"
-          $env:CACHE_RESTORE_KEY_0="$CACHE_RESTORE_KEY_1-${{ hashFiles('**/BUILD*') }}"
-          $env:CACHE_KEY="$CACHE_RESTORE_KEY_0-${{ github.sha }}"
-          echo "CACHE_RESTORE_KEY_2=$CACHE_RESTORE_KEY_2" >> "$GITHUB_ENV"
-          echo "CACHE_RESTORE_KEY_1=$CACHE_RESTORE_KEY_1" >> "$GITHUB_ENV"
-          echo "CACHE_RESTORE_KEY_0=$CACHE_RESTORE_KEY_0" >> "$GITHUB_ENV"
-          echo "CACHE_KEY=$CACHE_KEY" >> "$GITHUB_ENV"
+          $CACHE_RESTORE_KEY_2="${{ github.workflow }}"
+          $CACHE_RESTORE_KEY_1="$CACHE_RESTORE_KEY_2-${{ hashFiles('**/WORKSPACE', '**/.bazelrc') }}"
+          $CACHE_RESTORE_KEY_0="$CACHE_RESTORE_KEY_1-${{ hashFiles('**/BUILD*') }}"
+          $CACHE_KEY="$CACHE_RESTORE_KEY_0-${{ github.sha }}"
+          echo "CACHE_RESTORE_KEY_2=$CACHE_RESTORE_KEY_2" >> "$env:GITHUB_OUTPUT"
+          echo "CACHE_RESTORE_KEY_1=$CACHE_RESTORE_KEY_1" >> "$env:GITHUB_OUTPUT"
+          echo "CACHE_RESTORE_KEY_0=$CACHE_RESTORE_KEY_0" >> "$env:GITHUB_OUTPUT"
+          echo "CACHE_KEY=$CACHE_KEY" >> "$env:GITHUB_OUTPUT"
 
       - name: Restore bazel cache if cache is not being refreshed.
-        if: ${{ env.REFRESH_CACHE }} != 'true'
+        if: ! env.REFRESH_CACHE
         uses: actions/cache/restore@v4
         id: bazel-cache
         with:
           path: ~/.cache/bazel-windows
-          key: ${{ env.CACHE_KEY }}
+          key: ${{ steps.cache-keys.outputs.CACHE_KEY }}
           restore-keys: |
-            ${{ env.CACHE_RESTORE_KEY_0 }}-
-            ${{ env.CACHE_RESTORE_KEY_1 }}-
-            ${{ env.CACHE_RESTORE_KEY_2 }}-
+            ${{ steps.cache-keys.outputs.CACHE_RESTORE_KEY_0 }}-
+            ${{ steps.cache-keys.outputs.CACHE_RESTORE_KEY_1 }}-
+            ${{ steps.cache-keys.outputs.CACHE_RESTORE_KEY_2 }}-
 
       - name: Check cache hit
         run: |
@@ -64,7 +66,7 @@ jobs:
       - name: Run bazel build on Windows
         run: |
           bazel build --disk_cache=~/.cache/bazel-windows `
-            --define=DISABLE_HUGGINGFACE_TOKENIZER=1 -- //... `
+            --define=DISABLE_HUGGINGFACE_TOKENIZER=1 "--" //... `
             -//runtime/components:huggingface_tokenizer `
             -//runtime/components:huggingface_tokenizer_test
 
@@ -77,16 +79,16 @@ jobs:
       - name: Run bazel test on Windows
         run: |
           bazel test --disk_cache=~/.cache/bazel-windows `
-            --define=DISABLE_HUGGINGFACE_TOKENIZER=1 --test_output=errors -- //... `
+            --define=DISABLE_HUGGINGFACE_TOKENIZER=1 --test_output=errors "--" //... `
             -//runtime/components:huggingface_tokenizer_test
 
       - name: Remove cache if cache is being refreshed.
-        if: ${{ env.REFRESH_CACHE }} == 'true'
-        run: gh cache delete ${{ env.CACHE_KEY }} || echo "Cache not found"
+        if: env.REFRESH_CACHE
+        run: gh cache delete ${{ steps.cache-keys.outputs.CACHE_KEY }} || echo "Cache not found"
 
-      - name: Save bazel cache if new or changed on push.
+      - name: Save bazel cache if it's new or being refreshed.
         uses: actions/cache/save@v4
-        if: steps.bazel-cache.outputs.cache-hit != 'true'
+        if: env.REFRESH_CACHE || steps.bazel-cache.outputs.cache-hit != 'true'
         with:
           path: ~/.cache/bazel-windows
-          key: ${{ env.CACHE_KEY }}
+          key: ${{ steps.cache-keys.outputs.CACHE_KEY }}
